feat: introduce url whitelist
brentvollebregt/hit-counter pull request #8
Opened 2020-07-10 08:36 UTC by muety

Added the ability to specify a URL whitelist to prevent "spam"

2020-07-10 22:20 UTC, brentvollebregt requested changes

2020-07-10 22:20 UTC, brentvollebregt commented on server.py
> +
These have been added to the `count` routes, it would probably make sense to also add them to the `nocount` routes.

2020-07-10 22:20 UTC, brentvollebregt commented on config.py
> +    r'127\.0\.\d{1,3}\.\d{1,3}', r'^$'
```suggestion
    r'127\.0\.\d{1,3}\.\d{1,3}', 
    r'^$'
```

2020-07-10 22:20 UTC, brentvollebregt commented on server.py
> +        return config.FORBIDDEN_URL_MESSAGE
We should return a 403 like above

2020-07-10 22:58 UTC, brentvollebregt commented
Also, it would be good to have this mentioned in the README with a couple of examples.

2020-07-11 06:34 UTC, muety commented
Please review again :slightly_smiling_face:

2020-07-12 01:39 UTC, brentvollebregt commented
Just tested it myself and it looks good 👍 Thanks for the PR.

2020-07-12 01:39 UTC, merged